name: Publish plugin to pub.dev
on:
  push:
    branches:   
      - master
jobs:
  release:
    name: Release new plugin version to pub.dev
    runs-on: ubuntu-latest
    if: startsWith(github.event.commits[0].message, 'New library version')
    container:
      image:  google/dart:latest
    steps:
      - uses: actions/checkout@master
      
      - name: Update plugin version
        env:
          commit_msg: ${{ (github.event.commits[0].message) }}
        run: |
          version=$(grep -A 0 'version:' pubspec.yaml | sed 's/^.*: //')
          lastNumber=$(echo $version | grep -Eo '[0-9]+$')
          lastNumber=$((lastNumber+1))
          newVersion=$(echo "${version%.*}.${lastNumber}")

          sed -i "s/^version: .*$/version: $newVersion/" pubspec.yaml
          
          info=$(echo ${commit_msg//[[:blank:]]/} | cut -d ':' -f2)
          platform=$(echo $info | cut -d ',' -f1)
          version=$(echo $info | cut -d ',' -f2)
          
          echo $info

          echo "" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo -n "## " >> CHANGELOG.md
          echo "$newVersion - $platform, $version" >> CHANGELOG.md
          echo "" >> CHANGELOG.md


          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pubspec.yaml
          git commit -m "Release version $newVersion" -a
          git push origin master
          
