name: Publish plugin to pub.dev
on:
  push:
    branches:   
      - master
jobs:
  release:
    name: Release new plugin version to pub.dev
    runs-on: ubuntu-latest
    if: startsWith(github.event.commits[0].message, 'library file version')
    container:
      image:  google/dart:latest
    steps:
      - uses: actions/checkout@master
      
      - name : GITHUB CONTEXT
        env:
          GITHUB_CONTEXT: ${{ (github.event.commits[0].id) }}
        run: |
          git diff-tree --no-commit-id
      
      - name: Update plugin version
        run: |
          version=$(grep -A 0 'version:' pubspec.yaml | sed 's/^.*: //')
          lastNumber=$(echo $version | grep -Eo '[0-9]+$')
          lastNumber=$((lastNumber+1))
          newVersion=$(echo "${version%.*}.${lastNumber}")
    
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          fileName=$(git log --name-only --oneline HEAD --format= | grep -v '.{7} ')
          fileName2=$(git show --pretty="" --name-only $git_hash)     
                    
          sed -i "s/^version: .*$/version: $newVersion/" pubspec.yaml

          echo "" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo -n "## " >> CHANGELOG.md
          echo "$newVersion" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "$fileName2"  >> CHANGELOG.md 


          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pubspec.yaml
          git commit -m "Release version $newVersion" -a
          git push origin master
          
